nome = (input('Qual é o seu nome completo ?')).strip()
print('Seu nome completo em maiúsculo é : {}'.format(nome.upper()))
print('Seu nome em minúsculo é {} '.format(nome.lower()))
print('Seu nome completo tem {} letras'.format(len(nome)))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
n1 = nome.split()
print('O seu segundo nome é {}'.format(n1[2]))
n2 = nome.replace('santos','cardoso')
print(n2)
#print('Meu primeiro nome é {}'.format(n1[0]))
print(f'O meu primeiro nome é {n1[0]}')
print('Nome junto :{}'.format('='.join(n1)))
print(nome[4])
print('Quantos tem dessa (a) no nome ? {}'.format(nome.count('a',0,5)))
print('Onde posso encontrar (rib) ? Você pode encontrar na posição {}'.format(nome.find('rib')))

