algo = input('Digite algo: ')
print(type(algo))
print('Alphanumérico? ')
print(algo.isalnum())
print('Letras Maiúsculas? ')
print(algo.isupper())
print('letras Minúsculas? ')
print(algo.islower())
print('é ascii? ')
print(algo.isascii())
print('É só espaços? ')
print(algo.isspace())
